apiVersion: v1
kind: Pod
metadata:
  name: scmpod
  labels:
    app: scmbeckend
    environment: dev
spec:
  containers:
    - name: golang-container
      image: salomo07/scmproject:latest
      ports:
        - containerPort: 8080
