apiVersion: v1
kind: Pod
metadata:
  name: dind-pod
spec:
  containers:
  - name: dind-container
    image: docker:dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run
