apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  labels: 
    app: scm
    environment: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang-container
        image: golang:latest
