apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels: 
    app: redis
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-app
        image: redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          value: YVc1cGNHRnpjM2R2Y21SeVpXUnBjdz09
